# Generated by Django 4.2.3 on 2023-08-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_api', '0003_alter_bloodpressurewarning_measuretype_withings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodpressurewarning',
            name='measuretype_withings',
            field=models.IntegerField(),
        ),
    ]
