version: "3"

services:
  django:
    build:
      context: ./backend
    container_name: djangoapi_c
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DJANGO_SECRET_KEY=your-secret-key
      - DEBUG=True
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=3306
      - DJANGO_DB_NAME=thesis
      - DJANGO_DB_USER=root
      - DJANGO_DB_PASSWORD=
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - ./dashboard:/app/node_modules
