# Generated by Django 4.2.3 on 2023-07-31 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodPressureWarning',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('uuid', models.CharField(max_length=255)),
                ('deviceID', models.CharField(max_length=255)),
                ('measuretype_withings', models.IntegerField()),
                ('value', models.FloatField()),
                ('unit', models.IntegerField()),
                ('warning_code', models.CharField(choices=[('YELLOW', 'Code Yellow'), ('RED', 'Code Red')], max_length=10)),
            ],
            options={
                'db_table': 'bloodpressurewarning',
            },
        ),
        migrations.CreateModel(
            name='WithingsMeasureType',
            fields=[
                ('measuretype', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'withings_measuretype',
            },
        ),
        migrations.CreateModel(
            name='WithingsMeasure',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('uuid', models.CharField(max_length=100)),
                ('deviceID', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('measuretype_withings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_api.withingsmeasuretype')),
            ],
            options={
                'db_table': 'withings_measures',
            },
        ),
    ]
