# Generated by Django 4.2.3 on 2023-08-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withingsmeasure',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
