# Use an official MySQL image as a parent image
FROM mysql:5.7

# Environment variables for MySQL configuration
ENV MYSQL_ROOT_PASSWORD Mahdi1996
ENV MYSQL_DATABASE thesis

# Expose the MySQL port
EXPOSE 3306
